language: android

jdk: oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.3
    - android-25
    - extra-android-m2repository
    - extra-android-support

  licenses:
    - 'android-sdk-license.*'

before_script:
    - echo "sdk.dir=$ANDROID_HOME" > local.properties

script:
  - ./gradlew leanback-extensions:clean leanback-extensions:assembleRelease